#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#endif // GAME_CONSTANTS_H

const int EASY_ROWS = 9,
EASY_COLS = 9,
EASY_MINES = 10,
EASY_CELLS = EASY_ROWS * EASY_COLS;

const int MEDIUM_ROWS = 16,
MEDIUM_COLS = 16,
MEDIUM_MINES= 40,
MEDIUM_CELLS = MEDIUM_ROWS * MEDIUM_COLS;

const int HARD_ROWS = 16,
HARD_COLS = 30,
HARD_MINES= 99,
HARD_CELLS = HARD_ROWS * HARD_COLS;

enum Level{EASY, MEDIUM, HARD};

const int EASY_WINDOW_SIZE = 450,
MEDIUM_WINDOW_SIZE = 640,
HARD_WINDOW_WIDTH = 990,
HARD_WINDOW_HEIGHT = 0.55 * HARD_WINDOW_WIDTH ,
STATUS_PANEL_HEIGHT = 100;

const int EASY_CELL_SIZE = EASY_WINDOW_SIZE / EASY_COLS,
MEDIUM_CELL_SIZE = MEDIUM_WINDOW_SIZE / MEDIUM_COLS,
HARD_CELL_SIZE = HARD_WINDOW_WIDTH / HARD_COLS;

enum CellStatus{v0, v1, v2, v3, v4, v5, v6, v7, v8, MINE};
